development: &default
  adapter: postgresql
  database: hackjoy_development
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: hackjoy_test
  min_messages: warning

cucumber:
  <<: *test

production:
  <<: *default
  database: hackjoy_production
